### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by ValentinKaisermayer** [kibaekkim/DSP.jl#8]
[ Info: Precompiling Dsp [3f8b1f33-babd-5f87-a419-0f6725e165cf]
ERROR: LoadError: LoadError: error compiling Type: could not load library "libDsp"

It seems that I am missing [https://github.com/Argonne-National-Laboratory/DSP](url) but I really don't know how to install it.
If I clone the Julia package on my machine, how to point Dsp.jl to the folder containing the actual C library?

**Comment by kibaekkim** [comment]
This Julia package is just an interface to use the C library of DSP. You need to compile DSP for your machine. Please try to follow the description in [README.md](https://github.com/Argonne-National-Laboratory/DSP#installation) and let me know specific questions.
